package webkit2

/*
#include <webkit2/webkit2.h>
#include <stdlib.h>
*/
import "C"

var (
	// FindOptions
	FIND_OPTIONS_NONE                               = C.WebKitFindOptions(C.WEBKIT_FIND_OPTIONS_NONE)
	FIND_OPTIONS_CASE_INSENSITIVE                   = C.WebKitFindOptions(C.WEBKIT_FIND_OPTIONS_CASE_INSENSITIVE)
	FIND_OPTIONS_AT_WORD_STARTS                     = C.WebKitFindOptions(C.WEBKIT_FIND_OPTIONS_AT_WORD_STARTS)
	FIND_OPTIONS_TREAT_MEDIAL_CAPITAL_AS_WORD_START = C.WebKitFindOptions(C.WEBKIT_FIND_OPTIONS_TREAT_MEDIAL_CAPITAL_AS_WORD_START)
	FIND_OPTIONS_BACKWARDS                          = C.WebKitFindOptions(C.WEBKIT_FIND_OPTIONS_BACKWARDS)
	FIND_OPTIONS_WRAP_AROUND                        = C.WebKitFindOptions(C.WEBKIT_FIND_OPTIONS_WRAP_AROUND)

	// HitTestResultContext
	HIT_TEST_RESULT_CONTEXT_DOCUMENT  = C.WebKitHitTestResultContext(C.WEBKIT_HIT_TEST_RESULT_CONTEXT_DOCUMENT)
	HIT_TEST_RESULT_CONTEXT_LINK      = C.WebKitHitTestResultContext(C.WEBKIT_HIT_TEST_RESULT_CONTEXT_LINK)
	HIT_TEST_RESULT_CONTEXT_IMAGE     = C.WebKitHitTestResultContext(C.WEBKIT_HIT_TEST_RESULT_CONTEXT_IMAGE)
	HIT_TEST_RESULT_CONTEXT_MEDIA     = C.WebKitHitTestResultContext(C.WEBKIT_HIT_TEST_RESULT_CONTEXT_MEDIA)
	HIT_TEST_RESULT_CONTEXT_EDITABLE  = C.WebKitHitTestResultContext(C.WEBKIT_HIT_TEST_RESULT_CONTEXT_EDITABLE)
	HIT_TEST_RESULT_CONTEXT_SCROLLBAR = C.WebKitHitTestResultContext(C.WEBKIT_HIT_TEST_RESULT_CONTEXT_SCROLLBAR)

	// SnapshotOptions
	SNAPSHOT_OPTIONS_NONE                           = C.WebKitSnapshotOptions(C.WEBKIT_SNAPSHOT_OPTIONS_NONE)
	SNAPSHOT_OPTIONS_INCLUDE_SELECTION_HIGHLIGHTING = C.WebKitSnapshotOptions(C.WEBKIT_SNAPSHOT_OPTIONS_INCLUDE_SELECTION_HIGHLIGHTING)
)
