package webkit2

/*
#include <webkit2/webkit2.h>
#include <stdlib.h>

gchar* __WEBKIT_EDITING_COMMAND_COPY = WEBKIT_EDITING_COMMAND_COPY;
gchar* __WEBKIT_EDITING_COMMAND_CUT = WEBKIT_EDITING_COMMAND_CUT;
gchar* __WEBKIT_EDITING_COMMAND_PASTE = WEBKIT_EDITING_COMMAND_PASTE;
gchar* __WEBKIT_EDITING_COMMAND_REDO = WEBKIT_EDITING_COMMAND_REDO;
gchar* __WEBKIT_EDITING_COMMAND_SELECT_ALL = WEBKIT_EDITING_COMMAND_SELECT_ALL;
gchar* __WEBKIT_EDITING_COMMAND_UNDO = WEBKIT_EDITING_COMMAND_UNDO;
*/
import "C"

var (
	EDITING_COMMAND_COPY       = C.__WEBKIT_EDITING_COMMAND_COPY
	EDITING_COMMAND_CUT        = C.__WEBKIT_EDITING_COMMAND_CUT
	EDITING_COMMAND_PASTE      = C.__WEBKIT_EDITING_COMMAND_PASTE
	EDITING_COMMAND_REDO       = C.__WEBKIT_EDITING_COMMAND_REDO
	EDITING_COMMAND_SELECT_ALL = C.__WEBKIT_EDITING_COMMAND_SELECT_ALL
	EDITING_COMMAND_UNDO       = C.__WEBKIT_EDITING_COMMAND_UNDO
)
