package webkit2

/*
#include <webkit2/webkit2.h>
#include <stdlib.h>
*/
import "C"

var (
	// AuthenticationScheme
	AUTHENTICATION_SCHEME_DEFAULT                           = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_DEFAULT)
	AUTHENTICATION_SCHEME_HTTP_BASIC                        = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_HTTP_BASIC)
	AUTHENTICATION_SCHEME_HTTP_DIGEST                       = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_HTTP_DIGEST)
	AUTHENTICATION_SCHEME_HTML_FORM                         = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_HTML_FORM)
	AUTHENTICATION_SCHEME_NTLM                              = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_NTLM)
	AUTHENTICATION_SCHEME_NEGOTIATE                         = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_NEGOTIATE)
	AUTHENTICATION_SCHEME_CLIENT_CERTIFICATE_REQUESTED      = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_CLIENT_CERTIFICATE_REQUESTED)
	AUTHENTICATION_SCHEME_SERVER_TRUST_EVALUATION_REQUESTED = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_SERVER_TRUST_EVALUATION_REQUESTED)
	AUTHENTICATION_SCHEME_UNKNOWN                           = C.WebKitAuthenticationScheme(C.WEBKIT_AUTHENTICATION_SCHEME_UNKNOWN)

	// CacheModel
	CACHE_MODEL_DOCUMENT_VIEWER  = C.WebKitCacheModel(C.WEBKIT_CACHE_MODEL_DOCUMENT_VIEWER)
	CACHE_MODEL_WEB_BROWSER      = C.WebKitCacheModel(C.WEBKIT_CACHE_MODEL_WEB_BROWSER)
	CACHE_MODEL_DOCUMENT_BROWSER = C.WebKitCacheModel(C.WEBKIT_CACHE_MODEL_DOCUMENT_BROWSER)

	// ContextMenuAction
	CONTEXT_MENU_ACTION_NO_ACTION                    = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_NO_ACTION)
	CONTEXT_MENU_ACTION_OPEN_LINK                    = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OPEN_LINK)
	CONTEXT_MENU_ACTION_OPEN_LINK_IN_NEW_WINDOW      = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OPEN_LINK_IN_NEW_WINDOW)
	CONTEXT_MENU_ACTION_DOWNLOAD_LINK_TO_DISK        = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_LINK_TO_DISK)
	CONTEXT_MENU_ACTION_COPY_LINK_TO_CLIPBOARD       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_COPY_LINK_TO_CLIPBOARD)
	CONTEXT_MENU_ACTION_OPEN_IMAGE_IN_NEW_WINDOW     = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OPEN_IMAGE_IN_NEW_WINDOW)
	CONTEXT_MENU_ACTION_DOWNLOAD_IMAGE_TO_DISK       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_IMAGE_TO_DISK)
	CONTEXT_MENU_ACTION_COPY_IMAGE_TO_CLIPBOARD      = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_COPY_IMAGE_TO_CLIPBOARD)
	CONTEXT_MENU_ACTION_COPY_IMAGE_URL_TO_CLIPBOARD  = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_COPY_IMAGE_URL_TO_CLIPBOARD)
	CONTEXT_MENU_ACTION_OPEN_FRAME_IN_NEW_WINDOW     = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OPEN_FRAME_IN_NEW_WINDOW)
	CONTEXT_MENU_ACTION_GO_BACK                      = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_GO_BACK)
	CONTEXT_MENU_ACTION_GO_FORWARD                   = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_GO_FORWARD)
	CONTEXT_MENU_ACTION_STOP                         = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_STOP)
	CONTEXT_MENU_ACTION_RELOAD                       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_RELOAD)
	CONTEXT_MENU_ACTION_COPY                         = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_COPY)
	CONTEXT_MENU_ACTION_CUT                          = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_CUT)
	CONTEXT_MENU_ACTION_PASTE                        = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_PASTE)
	CONTEXT_MENU_ACTION_DELETE                       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_DELETE)
	CONTEXT_MENU_ACTION_SELECT_ALL                   = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_SELECT_ALL)
	CONTEXT_MENU_ACTION_INPUT_METHODS                = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_INPUT_METHODS)
	CONTEXT_MENU_ACTION_UNICODE                      = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_UNICODE)
	CONTEXT_MENU_ACTION_SPELLING_GUESS               = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_SPELLING_GUESS)
	CONTEXT_MENU_ACTION_NO_GUESSES_FOUND             = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_NO_GUESSES_FOUND)
	CONTEXT_MENU_ACTION_IGNORE_SPELLING              = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_IGNORE_SPELLING)
	CONTEXT_MENU_ACTION_LEARN_SPELLING               = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_LEARN_SPELLING)
	CONTEXT_MENU_ACTION_IGNORE_GRAMMAR               = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_IGNORE_GRAMMAR)
	CONTEXT_MENU_ACTION_FONT_MENU                    = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_FONT_MENU)
	CONTEXT_MENU_ACTION_BOLD                         = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_BOLD)
	CONTEXT_MENU_ACTION_ITALIC                       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_ITALIC)
	CONTEXT_MENU_ACTION_UNDERLINE                    = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_UNDERLINE)
	CONTEXT_MENU_ACTION_OUTLINE                      = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OUTLINE)
	CONTEXT_MENU_ACTION_INSPECT_ELEMENT              = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_INSPECT_ELEMENT)
	CONTEXT_MENU_ACTION_OPEN_VIDEO_IN_NEW_WINDOW     = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OPEN_VIDEO_IN_NEW_WINDOW)
	CONTEXT_MENU_ACTION_OPEN_AUDIO_IN_NEW_WINDOW     = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_OPEN_AUDIO_IN_NEW_WINDOW)
	CONTEXT_MENU_ACTION_COPY_VIDEO_LINK_TO_CLIPBOARD = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_COPY_VIDEO_LINK_TO_CLIPBOARD)
	CONTEXT_MENU_ACTION_COPY_AUDIO_LINK_TO_CLIPBOARD = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_COPY_AUDIO_LINK_TO_CLIPBOARD)
	CONTEXT_MENU_ACTION_TOGGLE_MEDIA_CONTROLS        = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_TOGGLE_MEDIA_CONTROLS)
	CONTEXT_MENU_ACTION_TOGGLE_MEDIA_LOOP            = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_TOGGLE_MEDIA_LOOP)
	CONTEXT_MENU_ACTION_ENTER_VIDEO_FULLSCREEN       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_ENTER_VIDEO_FULLSCREEN)
	CONTEXT_MENU_ACTION_MEDIA_PLAY                   = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_MEDIA_PLAY)
	CONTEXT_MENU_ACTION_MEDIA_PAUSE                  = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_MEDIA_PAUSE)
	CONTEXT_MENU_ACTION_MEDIA_MUTE                   = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_MEDIA_MUTE)
	CONTEXT_MENU_ACTION_DOWNLOAD_VIDEO_TO_DISK       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_VIDEO_TO_DISK)
	CONTEXT_MENU_ACTION_DOWNLOAD_AUDIO_TO_DISK       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_DOWNLOAD_AUDIO_TO_DISK)
	CONTEXT_MENU_ACTION_CUSTOM                       = C.WebKitContextMenuAction(C.WEBKIT_CONTEXT_MENU_ACTION_CUSTOM)

	// CookieAcceptPolicy
	COOKIE_POLICY_ACCEPT_ALWAYS         = C.WebKitCookieAcceptPolicy(C.WEBKIT_COOKIE_POLICY_ACCEPT_ALWAYS)
	COOKIE_POLICY_ACCEPT_NEVER          = C.WebKitCookieAcceptPolicy(C.WEBKIT_COOKIE_POLICY_ACCEPT_NEVER)
	COOKIE_POLICY_ACCEPT_NO_THIRD_PARTY = C.WebKitCookieAcceptPolicy(C.WEBKIT_COOKIE_POLICY_ACCEPT_NO_THIRD_PARTY)

	// CookiePersistentStorage
	COOKIE_PERSISTENT_STORAGE_TEXT   = C.WebKitCookiePersistentStorage(C.WEBKIT_COOKIE_PERSISTENT_STORAGE_TEXT)
	COOKIE_PERSISTENT_STORAGE_SQLITE = C.WebKitCookiePersistentStorage(C.WEBKIT_COOKIE_PERSISTENT_STORAGE_SQLITE)

	// CredentialPersistence
	CREDENTIAL_PERSISTENCE_NONE        = C.WebKitCredentialPersistence(C.WEBKIT_CREDENTIAL_PERSISTENCE_NONE)
	CREDENTIAL_PERSISTENCE_FOR_SESSION = C.WebKitCredentialPersistence(C.WEBKIT_CREDENTIAL_PERSISTENCE_FOR_SESSION)
	CREDENTIAL_PERSISTENCE_PERMANENT   = C.WebKitCredentialPersistence(C.WEBKIT_CREDENTIAL_PERSISTENCE_PERMANENT)

	// DownloadError
	DOWNLOAD_ERROR_NETWORK           = C.WebKitDownloadError(C.WEBKIT_DOWNLOAD_ERROR_NETWORK)
	DOWNLOAD_ERROR_CANCELLED_BY_USER = C.WebKitDownloadError(C.WEBKIT_DOWNLOAD_ERROR_CANCELLED_BY_USER)
	DOWNLOAD_ERROR_DESTINATION       = C.WebKitDownloadError(C.WEBKIT_DOWNLOAD_ERROR_DESTINATION)

	// FaviconDatabaseError
	FAVICON_DATABASE_ERROR_NOT_INITIALIZED   = C.WebKitFaviconDatabaseError(C.WEBKIT_FAVICON_DATABASE_ERROR_NOT_INITIALIZED)
	FAVICON_DATABASE_ERROR_FAVICON_NOT_FOUND = C.WebKitFaviconDatabaseError(C.WEBKIT_FAVICON_DATABASE_ERROR_FAVICON_NOT_FOUND)
	FAVICON_DATABASE_ERROR_FAVICON_UNKNOWN   = C.WebKitFaviconDatabaseError(C.WEBKIT_FAVICON_DATABASE_ERROR_FAVICON_UNKNOWN)

	// InjectedContentFrames
	INJECTED_CONTENT_FRAMES_ALL      = C.WebKitInjectedContentFrames(C.WEBKIT_INJECTED_CONTENT_FRAMES_ALL)
	INJECTED_CONTENT_FRAMES_TOP_ONLY = C.WebKitInjectedContentFrames(C.WEBKIT_INJECTED_CONTENT_FRAMES_TOP_ONLY)

	// InsecureContentEvent
	INSECURE_CONTENT_RUN       = C.WebKitInsecureContentEvent(C.WEBKIT_INSECURE_CONTENT_RUN)
	INSECURE_CONTENT_DISPLAYED = C.WebKitInsecureContentEvent(C.WEBKIT_INSECURE_CONTENT_DISPLAYED)

	// JavascriptError
	JAVASCRIPT_ERROR_SCRIPT_FAILED = C.WebKitJavascriptError(C.WEBKIT_JAVASCRIPT_ERROR_SCRIPT_FAILED)

	// LoadEvent
	LOAD_STARTED    = C.WebKitLoadEvent(C.WEBKIT_LOAD_STARTED)
	LOAD_REDIRECTED = C.WebKitLoadEvent(C.WEBKIT_LOAD_REDIRECTED)
	LOAD_COMMITTED  = C.WebKitLoadEvent(C.WEBKIT_LOAD_COMMITTED)
	LOAD_FINISHED   = C.WebKitLoadEvent(C.WEBKIT_LOAD_FINISHED)

	// NavigationType
	NAVIGATION_TYPE_LINK_CLICKED     = C.WebKitNavigationType(C.WEBKIT_NAVIGATION_TYPE_LINK_CLICKED)
	NAVIGATION_TYPE_FORM_SUBMITTED   = C.WebKitNavigationType(C.WEBKIT_NAVIGATION_TYPE_FORM_SUBMITTED)
	NAVIGATION_TYPE_BACK_FORWARD     = C.WebKitNavigationType(C.WEBKIT_NAVIGATION_TYPE_BACK_FORWARD)
	NAVIGATION_TYPE_RELOAD           = C.WebKitNavigationType(C.WEBKIT_NAVIGATION_TYPE_RELOAD)
	NAVIGATION_TYPE_FORM_RESUBMITTED = C.WebKitNavigationType(C.WEBKIT_NAVIGATION_TYPE_FORM_RESUBMITTED)
	NAVIGATION_TYPE_OTHER            = C.WebKitNavigationType(C.WEBKIT_NAVIGATION_TYPE_OTHER)

	// NetworkError
	NETWORK_ERROR_FAILED              = C.WebKitNetworkError(C.WEBKIT_NETWORK_ERROR_FAILED)
	NETWORK_ERROR_TRANSPORT           = C.WebKitNetworkError(C.WEBKIT_NETWORK_ERROR_TRANSPORT)
	NETWORK_ERROR_UNKNOWN_PROTOCOL    = C.WebKitNetworkError(C.WEBKIT_NETWORK_ERROR_UNKNOWN_PROTOCOL)
	NETWORK_ERROR_CANCELLED           = C.WebKitNetworkError(C.WEBKIT_NETWORK_ERROR_CANCELLED)
	NETWORK_ERROR_FILE_DOES_NOT_EXIST = C.WebKitNetworkError(C.WEBKIT_NETWORK_ERROR_FILE_DOES_NOT_EXIST)

	// PluginError
	PLUGIN_ERROR_FAILED               = C.WebKitPluginError(C.WEBKIT_PLUGIN_ERROR_FAILED)
	PLUGIN_ERROR_CANNOT_FIND_PLUGIN   = C.WebKitPluginError(C.WEBKIT_PLUGIN_ERROR_CANNOT_FIND_PLUGIN)
	PLUGIN_ERROR_CANNOT_LOAD_PLUGIN   = C.WebKitPluginError(C.WEBKIT_PLUGIN_ERROR_CANNOT_LOAD_PLUGIN)
	PLUGIN_ERROR_JAVA_UNAVAILABLE     = C.WebKitPluginError(C.WEBKIT_PLUGIN_ERROR_JAVA_UNAVAILABLE)
	PLUGIN_ERROR_CONNECTION_CANCELLED = C.WebKitPluginError(C.WEBKIT_PLUGIN_ERROR_CONNECTION_CANCELLED)
	PLUGIN_ERROR_WILL_HANDLE_LOAD     = C.WebKitPluginError(C.WEBKIT_PLUGIN_ERROR_WILL_HANDLE_LOAD)

	// PolicyDecisionType
	POLICY_DECISION_TYPE_NAVIGATION_ACTION = C.WebKitPolicyDecisionType(C.WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION)
	POLICY_DECISION_TYPE_NEW_WINDOW_ACTION = C.WebKitPolicyDecisionType(C.WEBKIT_POLICY_DECISION_TYPE_NEW_WINDOW_ACTION)
	POLICY_DECISION_TYPE_RESPONSE          = C.WebKitPolicyDecisionType(C.WEBKIT_POLICY_DECISION_TYPE_RESPONSE)

	// PolicyError
	POLICY_ERROR_FAILED                                  = C.WebKitPolicyError(C.WEBKIT_POLICY_ERROR_FAILED)
	POLICY_ERROR_CANNOT_SHOW_MIME_TYPE                   = C.WebKitPolicyError(C.WEBKIT_POLICY_ERROR_CANNOT_SHOW_MIME_TYPE)
	POLICY_ERROR_CANNOT_SHOW_URI                         = C.WebKitPolicyError(C.WEBKIT_POLICY_ERROR_CANNOT_SHOW_URI)
	POLICY_ERROR_FRAME_LOAD_INTERRUPTED_BY_POLICY_CHANGE = C.WebKitPolicyError(C.WEBKIT_POLICY_ERROR_FRAME_LOAD_INTERRUPTED_BY_POLICY_CHANGE)
	POLICY_ERROR_CANNOT_USE_RESTRICTED_PORT              = C.WebKitPolicyError(C.WEBKIT_POLICY_ERROR_CANNOT_USE_RESTRICTED_PORT)

	// PrintError
	PRINT_ERROR_GENERAL            = C.WebKitPrintError(C.WEBKIT_PRINT_ERROR_GENERAL)
	PRINT_ERROR_PRINTER_NOT_FOUND  = C.WebKitPrintError(C.WEBKIT_PRINT_ERROR_PRINTER_NOT_FOUND)
	PRINT_ERROR_INVALID_PAGE_RANGE = C.WebKitPrintError(C.WEBKIT_PRINT_ERROR_INVALID_PAGE_RANGE)

	// PrintOperationResponse
	PRINT_OPERATION_RESPONSE_PRINT  = C.WebKitPrintOperationResponse(C.WEBKIT_PRINT_OPERATION_RESPONSE_PRINT)
	PRINT_OPERATION_RESPONSE_CANCEL = C.WebKitPrintOperationResponse(C.WEBKIT_PRINT_OPERATION_RESPONSE_CANCEL)

	// ProcessModel
	PROCESS_MODEL_SHARED_SECONDARY_PROCESS     = C.WebKitProcessModel(C.WEBKIT_PROCESS_MODEL_SHARED_SECONDARY_PROCESS)
	PROCESS_MODEL_MULTIPLE_SECONDARY_PROCESSES = C.WebKitProcessModel(C.WEBKIT_PROCESS_MODEL_MULTIPLE_SECONDARY_PROCESSES)

	// SaveMode
	SAVE_MODE_MHTML = C.WebKitSaveMode(C.WEBKIT_SAVE_MODE_MHTML)

	// ScriptDialogType
	SCRIPT_DIALOG_ALERT   = C.WebKitScriptDialogType(C.WEBKIT_SCRIPT_DIALOG_ALERT)
	SCRIPT_DIALOG_CONFIRM = C.WebKitScriptDialogType(C.WEBKIT_SCRIPT_DIALOG_CONFIRM)
	SCRIPT_DIALOG_PROMPT  = C.WebKitScriptDialogType(C.WEBKIT_SCRIPT_DIALOG_PROMPT)

	// SnapshotError
	SNAPSHOT_ERROR_FAILED_TO_CREATE = C.WebKitSnapshotError(C.WEBKIT_SNAPSHOT_ERROR_FAILED_TO_CREATE)

	// SnapshotRegion
	SNAPSHOT_REGION_VISIBLE       = C.WebKitSnapshotRegion(C.WEBKIT_SNAPSHOT_REGION_VISIBLE)
	SNAPSHOT_REGION_FULL_DOCUMENT = C.WebKitSnapshotRegion(C.WEBKIT_SNAPSHOT_REGION_FULL_DOCUMENT)

	// TLSErrorsPolicy
	TLS_ERRORS_POLICY_IGNORE = C.WebKitTLSErrorsPolicy(C.WEBKIT_TLS_ERRORS_POLICY_IGNORE)
	TLS_ERRORS_POLICY_FAIL   = C.WebKitTLSErrorsPolicy(C.WEBKIT_TLS_ERRORS_POLICY_FAIL)

	// ViewMode
	VIEW_MODE_WEB    = C.WebKitViewMode(C.WEBKIT_VIEW_MODE_WEB)
	VIEW_MODE_SOURCE = C.WebKitViewMode(C.WEBKIT_VIEW_MODE_SOURCE)
)
